baseURL: https://wngxii.netlify.app
languageCode: en-us
title: WANG Xi's website
theme: "PaperMod"
paginate: 5

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true

hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45 # 谷歌统计
paginate: 3

minify:
    disableXML: true
    # minifyOutput: true

permalinks:
  post: "/:year/:month/:day/:title/"

defaultContentLanguage: en # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: English
    contentDir: content/english
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    profileMode:
      enabled: true
      title: Hello, I am WANG Xi!
      subtitle: Graduate student at Renmin University of China
      imageUrl: 1.png
      imageTitle: My Memoji
      imageWidth: 250
      imageHeight: 250
      buttons:
        - name: About
          url: about
        - name: Posts
          url: posts
        - name: Photographs
          url: photographs
    menu:
      main:
        - identifier: search
          name: Search
          url: search
          weight: 1
        - identifier: home
          name: Home
          url: /
          weight: 2
        - identifier: posts
          name: Posts
          url: posts
          weight: 3
        - identifier: photographs
          name: Photographs
          url: photographs
          weight: 4
        - identifier: archives
          name: Archives
          url: archives
          weight: 20
        - identifier: about
          name: About
          url: about
          weight: 50
  cn:
    languageName: 简体中文
    contentDir: content/chinese
    weight: 2
    taxonomies:
      category: 类别
      tag: 标签
      series: series
    profileMode:
      enabled: true
      title: " 你好，我是王曦！"
      subtitle: 재미있는 사람
      imageUrl: 1.png
      imageTitle: My Memoji
      imageWidth: 250
      imageHeight: 250
      buttons:
        - name: 关于我
          url: about
        - name: 日志
          url: posts
        - name: 摄影
          url: photographs
    menu:
      main:
        - identifier: search
          name: 搜索
          url: search
          weight: 1
        - identifier: home
          name: 主页
          url: /
          weight: 2
        - identifier: posts
          name: 日志
          url: posts
          weight: 3
        - identifier: photographs
          name: 摄影
          url: photographs
          weight: 4
        - identifier: archives
          name: 时间轴
          url: archives
          weight: 20
        - identifier: about
          name: 关于我
          url: about
          weight: 50
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: Go to bed early
  author: WANG Xi
  defaultTheme: auto
  disableThemeToggle: false
  DateFormat: 2006-01-02
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true
  ShowToc: true
  TocOpen: true
  comments: true
  socialIcons:
    - name: github
      url: https://github.com/wngxii
    - name: twitter
      url: https://twitter.com/tnqkrrrr
    - name: bilibili
      url: https://space.bilibili.com/160220375?spm_id_from=333.1007.0.0
    - name: email
      url: mailto:wang.xi.007@163.com
  analytics:
    SiteVerificationTag: XYZabc
  assets:
    favicon: img/Q.gif
    favicon16x16: img/Q.gif
    favicon32x32: img/Q.gif
    apple_touch_icon: Q.gif
    safari_pinned_tab: Q.gif
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 1
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
  twikoo:
    version: 1.4.11
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false
    style: darcula
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
